version: '3.8'
services:

  # Application
  app:
    build:
      context: .
      dockerfile: app.DOCKERFILE
    working_dir: /var/www
    networks:
      - laravel
    volumes:
      - ./:/var/www
  # Web Server
  web:
    build:
      context: .
      dockerfile: web.DOCKERFILE
    working_dir: /var/www
    networks:
      - laravel
    volumes:
      - ./:/var/www
    depends_on:
      - "app"
    ports:
      - 80:80
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

networks:
  laravel:
    name: laravel